# Generated by Django 5.0.6 on 2024-06-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='main.tag'),
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
